Make argument name more unique to avoid clashes(TypeError)
```python
Traceback (most recent call last):
  File "/tmp/kitchen/testing/salt/cloud/__init__.py", line 2349, in run_parallel_map_providers_query
    salt.utils.data.simple_types_filter(cloud.clouds[data["fun"]]()),
  File "/tmp/kitchen/testing/salt/loader.py", line 1182, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/tmp/kitchen/testing/salt/loader.py", line 2204, in run
    return self._last_context.run(self._run_as, method, *args, **kwargs)
  File "/tmp/kitchen/testing/.nox/pytest-cloud-3-coverage-false/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "/tmp/kitchen/testing/salt/loader.py", line 2219, in _run_as
    return method(*args, **kwargs)
  File "/tmp/kitchen/testing/salt/cloud/clouds/vultrpy.py", line 163, in list_nodes
    nodes = list_nodes_full()
  File "/tmp/kitchen/testing/salt/cloud/clouds/vultrpy.py", line 176, in list_nodes_full
    nodes = _query("server/list")
  File "/tmp/kitchen/testing/salt/cloud/clouds/vultrpy.py", line 530, in _query
    opts=__opts__,
  File "/tmp/kitchen/testing/salt/loader.py", line 1182, in __call__
    return self.loader.run(run_func, *args, **kwargs)
TypeError: run() got multiple values for argument 'method'
```